# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad2bded3b3ae7481f45d70ef50173c591c065f4fddea8e1f3934d2ff7bfc488d0691a3020932963cb2ec6f898c0c6efafedcedd47d040b36cd9015c16db8f234

test:
  secret_key_base: 51af0fa37c1b93086718259bb060844b8c80245e6702ad64e1900a08dce5379efe83e02e778864af3e9df5fbe9ce5662feb2ae4ec95b75a1435f2535b1bb3892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
